# Generated by Django 5.1.2 on 2025-03-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(blank=True, max_length=250, null=True)),
                ('texto_tarea', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=15)),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(max_length=250, unique=True)),
                ('contraseña', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='UsuTarea',
            fields=[
                ('id_usu_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarea', models.ForeignKey(blank=True, db_column='id_tarea', null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_app.tarea')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
            options={
                'db_table': 'usu_tarea',
            },
        ),
    ]
